### ISSUE TITLE
Valid repo file from collabora not present?

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-repo-collabora-code#1]
### Type of Report

Question/Enhancement

### Actual behaviour

A repofile is not used.

### Expected behaviour

A repofile should be used from upstream.
I wasnt able to find one. Is it true that there is none? oO

**Comment by donvipre** [comment]
https://www.collaboraoffice.com/code/#packages_for_linux_x86_64_platform

according to this: no :(
yum-config-manager doesn't seem to be the best option...

**Comment by daniel-schier** [comment]
ok, thanks a lot. bad habits of provider...
